version: '3.7'

networks:
  csi-flix:
    driver: bridge

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: core
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432/tcp"
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - csi-flix

  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://root:root@db:5432/core
    volumes:
      - ./back:/app
    networks:
      - csi-flix

  web:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '9000:9000'
    environment:
      - PORT=9000
    volumes:
      - ./front/src:/app/src
    networks:
      - csi-flix

volumes:
  postgres-db: