version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: core
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432/tcp"
    restart: always